services:
  - type: web
    name: ecommerce-sales-analytics
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: USE_SQLITE
        value: "1"
      - key: FLASK_SECRET_KEY
        generateValue: true